Autores:
---
- David Montaño Castro
- Sergio Israel Durán García

In [1]:
import sympy as sp
from sympy import Symbol, is_decreasing, is_increasing, Interval, S, tan, log,ln, pi, sqrt, sin, cos,csc, exp, Abs, Min, Max, oo  #<----- Aquí puedes agregar la función que desees.
from sympy.calculus.util import continuous_domain
from sympy.sets import Interval
import numpy as np
from numpy import linalg as LA
import pandas as pd
x = sp.Symbol("x")

<h1><center>EXAMEN 1 : ANÁLISIS NUMÉRICO</center></h1>

<h1><center>MÉTODOS PARA RAICES</center></h1>

Realiza los códigos en el lenguaje de programación R de los siguientes métodos para encontrar raíces de una función, considerando los criterios de paro visto en clase y mostrando la tabla comparativa de errores absolutos y relativos (2 puntos) :
- Método de Bisección.
- Método de Punto Fijo.
- Método de Newton Modificado.

Auxiliares
---

In [2]:
def continua(funcion,cota_inf,cota_sup):
    """
    Corrobora que una función es continua en un intervalo cerrado dado.
    
    La función solo retornará True si se cumple la condición.
    
    Parámetros:
    
    función : La función de interes a verificar si es continua.
    cota_inf : La cota inferior del intervalo.
    cota_sup : La cota superior del intervalo.
    """
    dominio = continuous_domain(funcion,x, S.Reals)
    return Interval(cota_inf,cota_sup).is_subset(dominio)

In [3]:
def derivable(funcion,cota_inf,cota_sup):
    """
    Corrobora que una función es derivable en un intervalo cerrado dado.
    
    La función solo retornará True si se cumple la condición.
    
    Parámetros:
    
    función : La función de interes a verificar si es derivable en el intervalo.
    cota_inf : La cota inferior del intervalo.
    cota_sup : La cota superior del intervalo. 
    """
    return continua(sp.diff(funcion,x),cota_inf,cota_sup)

In [4]:
def de_creciente(funcion,cota_inf,cota_sup):
    """
    Corrobora si la función DERIVADA de g(x) es creciente o decreciente en un intervalo cerrado dado.
    
    La función solo retornará True si se cumple la condición.
    
    Parámetros:
    
    función : La función de interes de la cual su derivada se quiere verificar si es creciente o decreciente en el intervalo.
    cota_inf : La cota inferior del intervalo.
    cota_sup : La cota superior del intervalo
    """
    return is_increasing(sp.diff(funcion,x),Interval(cota_inf,cota_sup).closure) or is_decreasing(sp.diff(funcion,x),Interval(cota_inf,cota_sup).closure)
    

In [5]:
def unicidad_k(funcion,cota_inf,cota_sup):
    """
    Corrobora que se cumpla la condición de unicidad para el algorítmo de punto fijo (|g'(x)|<k<1)
    
    Parámetros:
    
    función : La función de interes a verificar si cumple con la condición de unicidad en el intervalo.
    cota_inf : La cota inferior del intervalo.
    cota_sup : La cota superior del intervalo
    """
    if de_creciente(funcion, cota_inf,cota_sup):
        
        funcion = sp.diff(funcion,x)
        
        f_a = abs(funcion.subs(x,cota_inf))
        f_b = abs(funcion.subs(x,cota_sup))
    
        return max(f_a,f_b) < 1
        
    

In [6]:
def error_absoluto(ultimo,anterior):
    """
    Devuelve el error absoluto entre dos numeros.
    
    Parámetros:
    
    ultimo : primer numero.
    anterior : segundo numero.
    """
    return float(Abs(ultimo-anterior))

In [7]:
def error_relativo(ultimo,anterior):
    """
    Devuelve el error relativo entre dos numeros.
    
    Parámetros:
    
    numero1 : número menor o Xn-1
    numero2 : numero mayor o Xn
    """
    return float((ultimo-anterior)/ultimo)

Método de Bisección
---

1. Validad que $f(x)$ es continua en $[a,b] \in{R}$.
2. $f(a) * f(b) < 0$.
3. c = $\left( \displaystyle\frac{a+b}{2} \right) \longrightarrow$ punto medio y calculo $f(c)$.
4. $f(c) = 0 \longrightarrow$ Terminé
    - $> 0 \longrightarrow f(c) y f(b)$ son de signos iguales y $[a,c]$ porque $b = c$
    - $< 0 \longrightarrow f(c) y f(a)$ son de signos iguales y $[c,b]$ porque $a = c$
5. Repetir el proceso del 1 al 4 hasta el criterio de paro (# iteraciones y/o tolerancia)

In [8]:
#SIN_REP
def MET_BIS(funcion,a,b,itera):
    """
    Algorítmo Método de Bisección para encontrar raices de funciones no lineales.
    
    Parámetros:
    
    funcion: función a encontrar raíces.
    a = cota inferior del intervalo.
    b = cota superior del intervalo.
    itera = número de iteraciones.
    """
    
    x = sp.Symbol("x")
    errores_absolutos = []
    errores_relativos = []
    raices = []
    
    if continua(funcion,a,b):
        
        for i in range(1,itera + 1):
            
            f_a = funcion.subs(x,a)
            f_b = funcion.subs(x,b)
            
            if f_a * f_b < 0:
            
                c = (a+b)/2
                f_c = funcion.subs(x,c)
            
                if f_c == 0:
                    errores_absolutos.append(np.nan)
                    errores_relativos.append(np.nan)
                    raices.append(c)
                    print("La raiz que buscas es: ", c)
                    break
                    
                elif f_c > 0:
                    errores_absolutos.append(error_absoluto(c,b))
                    errores_relativos.append(error_relativo(c,b))
                    raices.append(c)
                    
                    b = c
                    
                elif f_c < 0:
                    errores_absolutos.append(error_absoluto(c,a))
                    errores_relativos.append(error_relativo(c,a))
                    raices.append(c)
                    
                    a = c
        
        
            else:
                print("El producto de tu invervalo no es menor de cero.")
    
            respuestas = pd.DataFrame({"Raices": raices,"errores absolutos": errores_absolutos,"errores relativos": errores_relativos})
    else:
        print("Tu funcion no es continua.")
    
    
    return respuestas

### Ejercicio de clase

In [9]:
MET_BIS(x**3 + 4*x**2-10,-5,2,100)

Raices  errores absolutos  errores relativos
0  -1.50000            3.50000          -2.333333
1   0.25000            1.75000           7.000000
2   1.12500            0.87500           0.777778
3   1.56250            0.43750          -0.280000
4   1.34375            0.21875           0.162791
..      ...                ...                ...
95  1.36523            0.00000           0.000000
96  1.36523            0.00000           0.000000
97  1.36523            0.00000           0.000000
98  1.36523            0.00000           0.000000
99  1.36523            0.00000           0.000000

[100 rows x 3 columns]

A lo mejor y el número de iteraciones que pasaste como parámetros fueron más de los suficientes. Por lo tanto, el siguiente decorador puede ayudarte a borrar las iteraciones repetidas; de esa manera recortarás la tabla y sabras la iteración exacta en la que converge tu función. Si deseas que sea así, solo descomenta al inicio de la función SIN_REP. Este se implementará para los dos siguientes algorítmos. <br>
__NOTA__: Si no te borra ningun reglón es porque los valores son diferentes a pesar de que parezcan iguales. 

In [10]:
def SIN_REP(f):
    def wrapper(funcion,a,b,itera):
        return f(funcion,a,b,itera).drop_duplicates(subset = "Raices")
    return wrapper

Método de punto fijo
---

El algorítmo consta de probar 2 elementos:
- EXISTENCIA:
    1. $x \in[a,b]$ y $g(x) \in C^1[a,b] $;
    2. $g(x) \in[a,b] $ $\forall x\in[a,b]$ 
    
- UNICIDAD:
    1. Si $g(x)$ está bien definida en $[a,b]$ y $\exists k \in R$ con $k<1$ tal que $|g'(x)|\leq k \hspace{.2cm}\forall  x \in [a,b]$. Para esto puede probarse que la función es decreciente o 
        creciente; podría agregarse que sean extrictamente decrecientes o crecientes, pero la finalidad de está condición es que no exista un punto intermedio entre las cotas del intervalo que 
        más grande que ellos en valor absoluto, lo cual puede verificarse solamente con la primera exigencia.
        



In [11]:
#SIN_REP
def MET_PF(funcion,a,b,itera):
    """
    Algorítmo Método de punto fijo para encontrar raices de funciones no lineales. El algorítmo tiene una deficiencia : el despeje de la función para que x = g(x) tiene que ser previo a
    que el usuario introduzca la función f(x) (la original).
    
    Parámetros:
    
    funcion : función cuya raiz se desea encontrar tal que x = g(x).
    a : cota inferior del intervalo.
    b : cota superior del intervalo.
    itera : número de iteraciones.
    """
    
    x = sp.Symbol("x")
    errores_absolutos = []
    errores_relativos = []
    raices = []
    
    if continua(funcion,a,b) and derivable(funcion,a,b): #CONDICIONES DE EXISTENCIA
        if unicidad_k(funcion,a,b): #CONDICION DE UNICIDAD
            
            x_0 = (a+b)/2
            
            for i in range(1,itera+1):

                y = funcion.subs(x,x_0)
                errores_absolutos.append(error_absoluto(y,x_0))
                errores_relativos.append(error_relativo(y,x_0))
                raices.append(y)
                x_0 = y     
        
        else:
            raise Exception("La función g(x) no cumple con la condición de unicidad.")
        
        respuestas = pd.DataFrame({"Raices": raices,"errores absolutos": errores_absolutos,"errores relativos": errores_relativos})
    
    else:
        raise Exception("La función g(x) no cumple con las condiciones de existencia.")
        
    return respuestas


### Ejercicio de clase

In [12]:
MET_PF(3/(x-4),-1,0,5)

Raices  errores absolutos  errores relativos
0  -0.666666666666667           0.166667           0.250000
1  -0.642857142857143           0.023810          -0.037037
2  -0.646153846153846           0.003297           0.005102
3  -0.645695364238411           0.000458          -0.000710
4  -0.645759087669280           0.000064           0.000099

### [Ejercicio Extra eje. 3](http://esfm.egormaximenko.com/numerical_methods/fixed_point_examples_es.pdf)

In [13]:
MET_PF((1/2)*(x+(4/x)),1.5,3,5)

Raices  errores absolutos  errores relativos
0  2.01388888888889       2.361111e-01      -1.172414e-01
1  2.00004789272031       1.384100e-02      -6.920332e-03
2  2.00000000057341       4.789215e-05      -2.394607e-05
3  2.00000000000000       5.734142e-10      -2.867071e-10
4  2.00000000000000       0.000000e+00       0.000000e+00

Método de Newton Modificado
---

El método funciona de una manera muy similar al Método de Newton pero ahora se le pide que la función f(x) admita una segunda derivada y está sea continua en el intervalo propuesto.

In [14]:
#SIN_REP
def MET_NEW_MOD(funcion,x_0,itera,a = -oo,b = oo):
    """
    Algorítmo Método de punto fijo para encontrar raices de funciones no lineales. Con el fin de no ocupar tanto tiempo, se piden dos limites en los que posible mente podría estar la raiz.
    Por default, el algorítmo asume continuidad en R, entonces [a,b] es un subconjunto de R. Si es continua en R entonces es continua en ese intervalo. 
    
    Parámetros:
    
    funcion : función cuya raiz se desea encontrar.
    x : punto inicial.
    a (opcional): cota inferior del intervalo. Por default es -oo
    b (opcional) : cota superior del intervalo. Por default es oo
    itera : número de iteraciones.
    """
    
    x = sp.Symbol("x")
    errores_absolutos = []
    errores_relativos = []
    raices = []
    
    if continua(funcion,a,b) and derivable(funcion,a,b): 
        if derivable(sp.diff(funcion,x),a,b): #CONDICION DE DOBLE DERIVABILIDAD
            
            primera = sp.diff(funcion,x)
            segunda = sp.diff(primera,x)
            
            for i in range(1,itera+1):
                
                y = x_0 - (funcion.subs(x,x_0) * primera.subs(x,x_0))/((primera.subs(x,x_0))**2 - funcion.subs(x,x_0) * segunda.subs(x,x_0))
                errores_absolutos.append(error_absoluto(y,x_0))
                errores_relativos.append(error_relativo(y,x_0))
                raices.append(y)
                x_0 = float(y)

                     
        
        else:
            raise Exception("La función f(x) no cumple con ser dos veces derivable.")
        
        respuestas = pd.DataFrame({"Raices": raices,"errores absolutos": errores_absolutos,"errores relativos": errores_relativos})
    
    else:
        raise Exception("La función f(x) no cumple con ser continua o derivable.")
        
    return respuestas


### Ejercicio de clase (Método Newton)

In [15]:
MET_NEW_MOD(x**5-x-1,-1,3)

Raices  errores absolutos  errores relativos
0                   -2           1.000000           0.500000
1  -0.0882123341139736           1.911788         -21.672566
2    -1.01185002000671           0.923638           0.912821

### [Ejercicio Extra](https://almedinablog.wordpress.com/metodo-newton-raphson/)

In [16]:
MET_NEW_MOD(3.5*x**2+6.8*x-8,1,2)

Raices  errores absolutos  errores relativos
0  0.817941952506596           0.182058          -0.222581
1  0.825604687177730           0.007663           0.009281

<h1><center>MÉTODOS PARA RESOLUCIÓN DE SISTEMAS DE ECUACIONES LINEALES</center></h1>

Realiza los códigos en el lenguaje de programación R de los siguientes métodos para solucionar sistemas de ecuaciones lineales (3 puntos):
- Método LU para Matrices Tridiagonales.
- Método de Jacobi.
- Método de Cholesky.

Auxiliares
---

In [17]:
def is_cuadrada(A):
    """
    Verifica si una matriz es cuadrada. Devuelve valor boolenano.
    
    Parámetros:
    
    A : Matriz a probar si es cuadrada.
    """
    return A.shape[0] == A.shape[1]

In [18]:
def is_nosingular(A):
    """
    Verifica si una matriz es no signular por medio de su determinante. Devuelve un valor boolenano.
    
    Parámetros:
    
    A: Matriz a probar si es no singular.
    """
    return np.linalg.det(A) != 0

In [19]:
def is_symmetric(A):
    """
    Verifica si la matriz es simétrica.
    
    Parámetros:
    
    A : Matriz a probar que es simétrica. 
    """
    return (A == A.T).all()

In [20]:
def is_def_pos(A):
    """
    Verifica que todos los valores propios de la matriz sean mayores a cero.
    
    A : Matriz a probar que sus valores propios son positivos.
    """
    v,w = LA.eig(A)
    return (v > 0).all()

Método LU para Matrices Tridiagonales
---

1. A tiene que ser cuadrada.
2. A no singular $<=>$ det(A) distinto de 0
3. A bien condicionada

### Método general (creado por confusión :()

In [21]:
def Matrix_LU(A,b, resultados = "los 3"):
    """
    Función para calcular la descomposición LU de una matriz cuadrada. 
    
    Parámetros:
    
    A : Matriz que se quiere descomoponer.
    b : Vector adjunto a la matriz A
    resultado (opcional) : por default se pasa el parámetro "los 3"
     - "los 3" : Devuelve L, U y la el vector solución al sistema.
     - "LyU" : Devuelve L y U.
     - "solucion" : Devuelve solo la solución al sistema.
     
     Ejemplos:
     
     Matrix_LU("4 -2 1 ; 20 -7 12 ; -8 13 17", "11;70;17", "solucion")
     
     Matrix_LU("2 -3 1;-4 9 2;6 -12 -2","3; 4; -2")
    """
    
    #Transformar parametros a objetos matriciales de Numpy
    
    A = np.matrix(A)
    b = np.matrix(b)
    
    if is_cuadrada(A) and is_nosingular(A):
        
        #Crear arreglos dummies para matrices L y U 
        
        L = np.zeros(A.shape) 
        U = np.zeros(A.shape)
        
        # U
        ## U1i con i = 1,...n
        for i in range(0,A.shape[0]):
            U[0,i] = A[0,i]
            
        # L
        ## Lii con i = 1,...n
        for i in range(0,A.shape[0]):
            L[i,i] = 1
        
        # L
        ## Lii con i = 1,...,n
        if A[0,0] == 0:
            raise Exception("Asegurate de que el primer elemento de tu matriz sea distinto de cero.")
        else:
            for i in range(1,A.shape[0]):
                L[i,0] = A[i,0]/A[0,0]    
            
        # U
        ## Uii con i = 2,...,n
        ## Uij con i = 2,...,n i<j
        # L
        ## Lji con j = 2,...,n
        for i in range(1,A.shape[0]):
    

            suma_Uii = 0
            for n in range(0,i):
                suma_Uii = suma_Uii + L[i,n] * U[n,i]
            U[i,i] = A[i,i] - suma_Uii
    

            for j in range(i,A.shape[0]):
                if i == j:
                    pass
            
                else:
                    suma_Uij = 0
                    for k in range(0,i):
                        suma_Uij = suma_Uij + L[i,k] * U[k,j]
                    U[i,j] = A[i,j] - suma_Uij
    

            for j in range(i,A.shape[0]):
                suma_Lij = 0
                for k in range(0,i):
                    suma_Lij = suma_Lij + L[j,k] * U[k,i]
                L[j,i] = (A[j,i]-suma_Lij)/U[i,i]
    
    
    else:
        print("Tu matriz no es cuadrada o es singular.")
    
    if resultados == "los 3":
        return np.linalg.inv(A) * b, L, U
    elif resultados == "LyU":
        return L,U
    elif resultados == "solucion":
        return np.linalg.inv(A) * b

### Ejercicio de clase

In [22]:
Matrix_LU("4 -2 1 ; 20 -7 12 ; -8 13 17", "11;70;17", "solucion" )

matrix([[ 1.],
        [-2.],
        [ 3.]])

### Ejercicios Extra 

In [23]:
Matrix_LU("2 -3 1;-4 9 2;6 -12 -2","3; 4; -2")

(matrix([[4.],
         [2.],
         [1.]]),
 array([[ 1.,  0.,  0.],
        [-2.,  1.,  0.],
        [ 3., -1.,  1.]]),
 array([[ 2., -3.,  1.],
        [ 0.,  3.,  4.],
        [ 0.,  0., -1.]]))

In [24]:
Matrix_LU("1 -1 2; 2 1 -1; 1 2 1","3;1;5")

(matrix([[0.75],
         [1.25],
         [1.75]]),
 array([[1., 0., 0.],
        [2., 1., 0.],
        [1., 1., 1.]]),
 array([[ 1., -1.,  2.],
        [ 0.,  3., -5.],
        [ 0.,  0.,  4.]]))

### Método para matrices tridiagonales

In [257]:
def Matrix_LU_TRI(A,b,resultados = "los 3"):
    """
    Función que devuleve la descomposición L y U de una matriz tridiagonal, incluyendo la respuesta al sistema.
    
    ESTE MÉTODO SUPONE LA DIAGONAL DE UNOS EN LA MATRIZ U.
    
    Parámetros:
    
    A : Matriz que se quiere descomoponer.
    b : Vector adjunto a la matriz A
    resultado (opcional) : por default se pasa el parámetro "los 3"
     - "los 3" : Devuelve L, U y la el vector solución al sistema.
     - "LyU" : Devuelve L y U.
     - "solucion" : Devuelve solo la solución al sistema.
     
     Ejemplos:
     
     Matrix_LU("4 -2 1 ; 20 -7 12 ; -8 13 17", "11;70;17", "solucion")
     
     Matrix_LU("2 -3 1;-4 9 2;6 -12 -2","3; 4; -2")
    """
    
    #Transformar parametros a objetos matriciales de Numpy
    
    A = np.matrix(A)
    b = np.matrix(b)
    
    if is_cuadrada(A) and is_nosingular(A):
        
        #Crear arreglos dummies para matrices L y U 
        
        L = np.zeros(A.shape) 
        U = np.zeros(A.shape)
        
        #1
        L[0,0] = A[0,0]

        for i in range(A.shape[0]):
            U[i,i] = 1

        #2
        for i in range(1,A.shape[0]):
            L[i,i-1] = A[i,i-1]

        #3
        for i in range(1,A.shape[0]):
            L[i,i] = A[i,i] - (L[i,i-1] * A[i-1,i])/(L[i-1,i-1])
        

        #4
        for i in range(1,A.shape[0]):
            U[i-1,i] = (A[i,i]-L[i,i])/(L[i,i-1])
   
        L_inv = np.linalg.inv(L)
        U_inv = np.linalg.inv(U)

        Y = L_inv * b
        X = U_inv * Y

    else:
        print("Tu matriz no es cuadrada o es singular.")
    
    if resultados == "los 3":
        return X, L, U
    elif resultados == "LyU":
        return L,U
    elif resultados == "solucion":
        return X
    

### Ejercicio 6 Tarea

In [258]:
Matrix_LU_TRI("2 -1 0;-1 2 -1; 0 -1 2","3;-3;1")

(matrix([[ 1.],
         [-1.],
         [ 0.]]),
 array([[ 2.        ,  0.        ,  0.        ],
        [-1.        ,  1.5       ,  0.        ],
        [ 0.        , -1.        ,  1.33333333]]),
 array([[ 1.        , -0.5       ,  0.        ],
        [ 0.        ,  1.        , -0.66666667],
        [ 0.        ,  0.        ,  1.        ]]))

Método de Jacobi
---

Método que requiere tener una matriz con diagonal dominane. Para más información haz click [AQUI](https://es.wikipedia.org/wiki/Matriz_de_diagonal_estrictamente_dominante#:~:text=En%20matem%C3%A1ticas%2C%20y%20concretamente%20en,de%20elementos%20de%20esa%20fila.). 
1. Despejar cada reglón de la matriz de tal manera que $x_i = \left( \displaystyle\frac{b_i -  \sum_{j=1,i \neq j }^{n} a_{ij}x_j  }{a_{ii}} \right) $ 
2. Vector inicial $\bar{X_0}$ = (0,...,0)

In [290]:
def Matrix_Jacobi(A,b,itera):
    """
    Función para calcular la solución de un sistema de ecuaciones por medio del método de Jacobi.
    
    EL USUARIO TIENE QUE ASEGURARSE DE QUE LA MATRIZ QUE SEA PASADA COMO PÁRAMETRO TENGA DIAGONAL DOMINANTE, YA QUE LA FUNCIÓN NO TIENE IMPLEMENTADA ESA OPCIÓN.
    
    Parámetros:
    
    A : Matriz a la cual se quiere aplicar el método de Jacobi.
    b : vector adjunto a la matriz A.
    """
    
    # Transformar los parámetros a matrices de numpy
    
    A = np.matrix(A)
    b = np.matrix(b)
    x_0 = np.zeros((A.shape[0],1))
    
    if is_cuadrada(A):
        
        D = np.zeros(A.shape)
        for i in range(A.shape[0]):
            D[i,i] =A[i,i]
    
        for h in range(1,itera+1):
            
            D_inv = np.linalg.inv(D)
            Q = A-D

            X = D_inv * (b - Q * (x_0))
            x_0 = X
    
    else: 
        print("Tu matriz no es cuadrada")
        
    return x_0
        

### Ejercicio de clase

In [294]:
Matrix_Jacobi("3 -1 1; 3 6 2; 3 3 7","1;0;4",23)

matrix([[ 0.03508772],
        [-0.2368421 ],
        [ 0.65789474]])

### [Ejercicio extra Pregunta 3](http://www.lcc.uma.es/~villa/tn/tema05res.pdf)

In [295]:
Matrix_Jacobi("10 3 1; 2 -10 3; 1 3 10","14; -5; 14",6)

matrix([[1.000251],
        [1.005795],
        [1.000251]])

Factorización de Cholesky
---

1. A es cuadrada.
2. A es no singular.
3. A es simétrica.
4. A es definida positiva.

In [357]:
def Matrix_Cholesky(A,b, resultados = "los 3"):
    """
    Función para calcular la factorización de Cholesky de una matriz cuadrada.
    
    Parámetros : 
    
    A : Matriz que se quiere descomoponer.
    b : Vector adjunto a la matriz A
    resultado (opcional) : por default se pasa el parámetro "los 3"
     - "los 3" : Devuelve L, L transpuesta y el vector solución al sistema.
     - "LyL_trans" : Devuelve L y L transpuesta
     - "solucion" : Devuelve solo la solución al sistema.
     
     Ejemplos:
     
     Matrix_Cholesk("4 -2 1 ; 20 -7 12 ; -8 13 17", "11;70;17", "solucion")
     
     Matrix_Cholesky("2 -3 1;-4 9 2;6 -12 -2","3; 4; -2") 
    """
    
    # Transformar los parámetros a matrices de numpy
    
    A = np.matrix(A)
    b = np.matrix(b)
    
    
    if is_cuadrada(A) and is_nosingular(A) and is_symmetric(A) and is_def_pos(A):
        
        #Crear matriz L para guardar los datos
        L = np.zeros(A.shape) 
        
        for i in range(A.shape[0]):
            for j in range(A.shape[0]):
                suma = 0
                for k in range(j):
                    suma = suma + L[i,k] * L[j,k]
        
                if i == j:
                    L[i,j] = sqrt(A[i,i] - suma)
                else:
                    with np.errstate(divide = "raise",invalid = "raise"):
                        try:
                            L[i,j] = (A[i,j]- suma) / L[j,j]
                        except FloatingPointError:
                            L[i,j] = 0
        
        #Soluciones
        
        L_trans = np.transpose(L)
        Y = np.linalg.inv(L) * b
        X = np.linalg.inv(L_trans) * Y
        
    
    

    else:
        raise Exception("Tu matriz no cumple alguno(s) de las condiciones para aplicar este método.")
        
    if resultados == "los 3":
        return X, L, L_trans
    elif resultados == "LyL_trans":
        return L,L_trans
    elif resultados == "solucion":
        return X

### Ejercicio de clase

In [358]:
Matrix_Cholesky("2 0 -1; 0 2 1; -1 1 2","-1;7;7")

(matrix([[1.],
         [2.],
         [3.]]),
 array([[ 1.41421356,  0.        ,  0.        ],
        [ 0.        ,  1.41421356,  0.        ],
        [-0.70710678,  0.70710678,  1.        ]]),
 array([[ 1.41421356,  0.        , -0.70710678],
        [ 0.        ,  1.41421356,  0.70710678],
        [ 0.        ,  0.        ,  1.        ]]))

### [Ejercicio Extra Pag. 6](http://www.ugr.es/~prodelas/ftp/Ciencias/Geologia/Tema2.pdf)

In [362]:
Matrix_Cholesky("2 -1 1; -1 3 -2; 1 -2 4","1;2;0")

(matrix([[0.92307692],
         [1.23076923],
         [0.38461538]]),
 array([[ 1.41421356,  0.        ,  0.        ],
        [-0.70710678,  1.58113883,  0.        ],
        [ 0.70710678, -0.9486833 ,  1.61245155]]),
 array([[ 1.41421356, -0.70710678,  0.70710678],
        [ 0.        ,  1.58113883, -0.9486833 ],
        [ 0.        ,  0.        ,  1.61245155]]))